# Generated by Django 2.2.7 on 2019-11-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0002_auto_20191113_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='workout_plan.User'),
        ),
    ]
